- hosts: webserver

  roles: 
    - server
    - apache2
    - php
    - mysql
    - wordpress

- hosts: logserver
  become: yes

  roles: 
    - generic-debian
    - logserver

- hosts: moniserv

  roles: 
    - moniserv
